[package]
name = "playfs"
version = "0.1.0"
authors = ["RÃ©mi NICOLE <minijackson@riseup.net>"]

[dependencies]
fuse_mt = "0.4.0"
rusqlite = "0.13.0"
clap = "2.24.2"
log = "0.3"
simplelog = "0.4"
time = "0.1.37"
libc = "0.2.23"
